### ISSUE TITLE
ブロックチェーンの学習

### ISSUE THREAD

**Issue by MKDir43** [ousquid/study#15]
言葉は聞くけどよく分かっておらず。
書籍：ブロックチェーン・プログラミング 仮想通貨入門 (KS情報科学専門書)
言語はRuby。

**Comment by zonkyy** [comment]
https://cryptozombies.io/jp/

**Comment by koiking213** [comment]
詳解 ビットコイン
3章まで終了

**Comment by MKDir43** [comment]
詳解 ビットコイン ―ゼロから設計する過程で学ぶデジタル通貨システム を通読完了。https://www.oreilly.co.jp/books/9784873119083/
