### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by koiking213** [ousquid/study#26]
よく聞くけど何者

**Comment by MKDir43** [comment]
自分も気になる。関連してHelmも何者

**Comment by MKDir43** [comment]
https://jaco.udcp.info/entry/2020/12/08/215058 のコンテナ未経験新人が学ぶコンテナ技術入門を読んだ

- Node>Pod>Containerという階層構造あり。
- Pod処理内容はServiceというIP:Portを指定できるフロントエンドから取得。
- MasterのControllerがPodをデプロイ。以下のパターンあり
  *  ReplocaSet(ControllerはDeployment), StatefulSet, DaemonSet, Job/CronJob
